DarkRisesWebBundle_counterpage:
    pattern:  /register/
    defaults: { _controller: DarkRisesWebBundle:Default:register}
DarkRisesWebBundle_gallerypage:
    pattern:  /gallery/
    defaults: { _controller: DarkRisesWebBundle:Default:gallery}
DarkRisesWebBundle_sendfanartpage:
    pattern:  /sendFanart/
    defaults: { _controller: DarkRisesWebBundle:Default:sendfanart}
DarkRisesWebBundle_adminfanartuploadpage:
    pattern:  /admin/fanart/upload/
    defaults: { _controller: DarkRisesWebBundle:Admin:uploadFanart}
DarkRisesWebBundle_adminmainpage:
    pattern: /admin/
    defaults: { _controller: DarkRisesWebBundle:Admin:main}
DarkRisesWebBundle_localefanartpersonalpage:
    pattern:  /{_locale}/fanart/{autor}/{id}/
    defaults: { _controller: DarkRisesWebBundle:Default:fanartpersonal, autor: "empty", _locale: es, id: "empty" }
    requirements:
        _locale: en|es
DarkRisesWebBundle_localefanartgalleryfilterpage:
    pattern:  /{_locale}/fanart/{filter}/
    defaults: { _controller: DarkRisesWebBundle:Default:fanartgallery, filter: "id", _locale: es}
    requirements:
        _locale: en|es
DarkRisesWebBundle_localefanartgallerypage:
    pattern:  /{_locale}/fanart/
    defaults: { _controller: DarkRisesWebBundle:Default:fanartgallery, filter: "empty", _locale: es}
    requirements:
        _locale: en|es
DarkRisesWebBundle_localesecondhomepage:
    pattern:  /{_locale}/{name}/{second}/
    defaults: { _controller: DarkRisesWebBundle:Default:index, name: "empty", _locale: es, second: "empty" }
    requirements:
        _locale: en|es
DarkRisesWebBundle_localehomepage:
    pattern:  /{_locale}/{name}/
    defaults: { _controller: DarkRisesWebBundle:Default:index, name: "empty", _locale: es, second: "empty" }
    requirements:
        _locale: en|es
DarkRisesWebBundle_localeindexpage:
    pattern:  /{_locale}/
    defaults: { _controller: DarkRisesWebBundle:Default:index, name: "empty", _locale: es, second: "empty" }
    requirements:
        _locale: es|en
DarkRisesWebBundle_fanartpersonalpage:
    pattern:  /fanart/{autor}/{id}/
    defaults: { _controller: DarkRisesWebBundle:Default:fanartpersonal, autor: "empty", id: "empty" }
DarkRisesWebBundle_fanartgalleryfilterpage:
    pattern:  /fanart/{filter}/
    defaults: { _controller: DarkRisesWebBundle:Default:fanartgallery, filter: "empty"}
DarkRisesWebBundle_fanartgallerypage:
    pattern:  /fanart/
    defaults: { _controller: DarkRisesWebBundle:Default:fanartgallery, filter: "empty"}
DarkRisesWebBundle_secondhomepage:
    pattern:  /{name}/{second}/
    defaults: { _controller: DarkRisesWebBundle:Default:index, name: "empty", second: "empty" }
DarkRisesWebBundle_wallapershomepage:
    pattern:  /wallpaper/highres/{number}/{address}
    defaults: { _controller: DarkRisesWebBundle:Default:wallpaper, number: "empty", address: "empty"}
DarkRisesWebBundle_indexpage:
    pattern:  /{name}/ 
    defaults: { _controller: DarkRisesWebBundle:Default:index, name: "empty", second: "empty"}
DarkRisesWebBundle_homepage:
    pattern:  /
    defaults: { _controller: DarkRisesWebBundle:Default:index, name: "empty", second: "empty"}
    