DarkRisesWebBundle_counterpage:
    pattern:  /register/
    defaults: { _controller: DarkRisesWebBundle:Default:register}
DarkRisesWebBundle_adminfanartpage:
    pattern:  /admin/fanart/
    defaults: { _controller: DarkRisesWebBundle:Admin:uploadFanart}
DarkRisesWebBundle_localesecondhomepage:
    pattern:  /{_locale}/{name}/{second}/
    defaults: { _controller: DarkRisesWebBundle:Default:index, name: "empty", _locale: es, second: "empty" }
    requirements:
        _locale: en|es
DarkRisesWebBundle_localehomepage:
    pattern:  /{_locale}/{name}/
    defaults: { _controller: DarkRisesWebBundle:Default:index, name: "empty", _locale: es, second: "empty" }
    requirements:
        _locale: en|es
DarkRisesWebBundle_localeindexpage:
    pattern:  /{_locale}/
    defaults: { _controller: DarkRisesWebBundle:Default:index, name: "empty", _locale: es, second: "empty" }
    requirements:
        _locale: es|en
DarkRisesWebBundle_secondhomepage:
    pattern:  /{name}/{second}/
    defaults: { _controller: DarkRisesWebBundle:Default:index, name: "empty", second: "empty" }
DarkRisesWebBundle_wallapershomepage:
    pattern:  /wallpaper/highres/{number}/{address}
    defaults: { _controller: DarkRisesWebBundle:Default:wallpaper, number: "empty", address: "empty"}
DarkRisesWebBundle_indexpage:
    pattern:  /{name}/ 
    defaults: { _controller: DarkRisesWebBundle:Default:index, name: "empty", second: "empty"}
DarkRisesWebBundle_homepage:
    pattern:  /
    defaults: { _controller: DarkRisesWebBundle:Default:index, name: "empty", second: "empty"}
    