parameters:
#    dark_rises_web.example.class: DarkRises\WebBundle\Example

services:
#    dark_rises_web.example:
#        class: %dark_rises_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    security.authentication.factory.facebook:
        class: Acme\DemoBundle\Facebook\FacebookFactory
        public: false
        tag:
            name: security.listener.factory
